name: Check latest version

on:
  pull_request:
  push:
    tags:
      - "v*"
    branches:
      - '**'
jobs:
  check-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build binaries
        id: build-tags
        run: |
          ./ci_env.sh

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Get base branch
        id: get-base-branch
        run: |
          BASE_BRANCH=${{ github.event.base_ref }}
          BASE_BRANCH=${BASE_BRANCH#refs/heads/}
          echo "base_branch=$BASE_BRANCH" >> $GITHUB_ENV
          echo "Base Branch: $BASE_BRANCH"

      - name: Only run on latest tag
        if: ${{ github.ref == format('refs/tags/{0}', steps.get-tag-info.outputs.latest_tag) }}
        run: echo "Running on latest tag"
